### ISSUE TITLE
Missing custom.list file crashes the script

### ISSUE THREAD

**Issue by Cartache** [vmstan/gravity-sync#86]
If the file custom.list got missing in the destination folder the script crashes without finishing the job.

**Configuration:**
 - OS for Primary/Secondary: Ubuntu 18.04.5
 - Platform for Primary/Secondary: vm on Unraid / OEM server 
 - Gravity Sync Version: 2.2.0
 - Pi-hole Versions: v5.1.2

**Comment by vmstan** [comment]
So there is a custom.list on the primary, but not on the secondary, and it's crashing? Just want to confirm.

**Comment by Cartache** [comment]
> So there is a custom.list on the primary, but not on the secondary, and it's crashing? Just want to confirm.

Yes, this is exactly what happened. I simply copy over the missing file to the secondary pi-hole and re-run successfully the script.

**Comment by vmstan** [comment]
Fixed in 2.2.1

**Comment by CestDiego** [comment]
Just wanted to share that I'm on 2.2.1 and I still experienced this problem. I couldn't even copy the file with rsync because /etc/pihole has permissions for user `pihole` and not `pi`.

I ended up having to create a local DNS config in the secondary UI, and then run the ./gravity-sync. Which worked successfully :)

**Comment by vmstan** [comment]
Bug must not be fully squashed, thanks for the heads up.

**Comment by vmstan** [comment]
Please update your install to 2.2.2 and test again.

`./gravity-sync.sh update`
